### ISSUE TITLE
树状结构 

### ISSUE THREAD

**Issue by fromIRIS** [TongchengQiu/webpack-best-practice#1]
想问下下图这种结构在markdown中是如何实现的？
![image](https://cloud.githubusercontent.com/assets/8492963/11916625/1c874fa0-a71a-11e5-8a0f-187a1930b969.png)

**Comment by fromIRIS** [comment]
已解决。。
npm 搜 `tree` 有很多解决方案。

**Comment by TongchengQiu** [comment]
不好意思现在才看到，我给你源代码吧：
.
├── app                 #开发目录
|   ├──assets           #存放静态资源
|   |   ├──datas        #存放数据 json 文件
|   |   ├──images       #存放图片资源文件
|   |   └──styles       #存放全局sass变量文件和reset文件
|   ├──lib
|   |   ├──components   #存放数据 模块组件 文件
|   |   |   └──Header
|   |   |       ├──Header.jsx
|   |   |       └──Header.scss
|   |   |  
|   |   └──utils        #存放utils工具函数文件
|   |
|   └──views
|       ├──Index        #入口文件
|       |   ├──Index.html #html文件
|       |   ├──Index.jsx
|       |   └──Index.scss
|       └──Index2
├── dist                #发布目录
├── node_modules        #包文件夹
├── .gitignore  
├── .jshintrc  
├── webpack.config.js   #webpack配置文件
└── package.json

在前后加  ``` 改成代码格式就可以了

**Comment by fromIRIS** [comment]
@TongchengQiu  我想了解的是如何快速 生成 tree状格式的段落。 你是手打的吗。。。
