### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Gaohaoyang** [TongchengQiu/webpack-best-practice#2]
大概看了你继续写的芝麻开门的代码，觉得挺不错的。向你学习！

我当时也是初学webpack，所以有些地方我写的不够优雅，辛苦你了。

**Comment by TongchengQiu** [comment]
之前没用过  AMD  模块加载的风格，有点不熟悉 😂，写的比较坑，而且好久没用 jquery 了。
有机会多多交流交流～

**Comment by Gaohaoyang** [comment]
嗯，那你一般用什么模块化？

用什么框架？

**Comment by TongchengQiu** [comment]
es6的模块化特性，或者 CMD ，因为之前  nodejs  用的比较多。 用webpack的话都很方便的
